### ISSUE TITLE
cant find the discord's user ID

### ISSUE THREAD

**Issue by sambhavsaxena** [NuroDev/nuro.dev#54]
I'm getting the following error while adding my account user ID, not sure what's wrong
![image](https://user-images.githubusercontent.com/76242518/181102436-36ec32b4-29dc-45f1-855a-09feff7bacf9.png)

help needed

**Comment by NuroDev** [comment]
Just pushed a fix to catch this error better.

This error is usually thrown when Lanyard failed to fetch your user data.
The 2 obvious checks I need to ask are this:

1. Check to make sure your Discord ID is correct (EG: `NAME#0000`)
2. Make sure you're [in the Lanyard Discord server](https://github.com/Phineas/lanyard/#get-started-in--10-seconds) as that will actually allow for Discord presence detection.
